### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sybrendotinga** [standard/eslint-config-standard#104]
It seems that with eslint-config-standard enabled in my Vue project I can not run the eslint command anymore. While running webpack I don't get this error, but when I run `eslint` get the following error:

```
$ eslint . --ext .js,.vue
Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.match] (<anonymous>)
    at String.match (native)
    at Literal (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/rules/no-octal-escape.js:32:40)
    at listeners.(anonymous function).forEach.listener (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/safe-emitter.js:47:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/safe-emitter.js:47:38)
    at NodeEventGenerator.applySelector (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:280:22)
    at NodeEventGenerator.enterNode (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/util/node-event-generator.js:294:14)
    at CodePathAnalyzer.enterNode (/Users/sybrendotinga/Documents/Webprojects/frontend/vue-boilerplate/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:608:23)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**package.json**
```
{
  "dependencies": {},
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-eslint": "^7.2.3",
    "babel-loader": "^7.1.2",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-polyfill": "^6.26.0",
    "babel-preset-env": "^1.6.1",
    "babel-preset-stage-2": "^6.22.0",
    "babel-runtime": "^6.26.0",
    "eslint": "^4.14.0",
    "eslint-config-standard": "^11.0.0-beta.0",
    "eslint-friendly-formatter": "^3.0.0",
    "eslint-loader": "^1.9.0",
    "eslint-plugin-import": "^2.8.0",
    "eslint-plugin-node": "^5.2.1",
    "eslint-plugin-promise": "^3.6.0",
    "eslint-plugin-standard": "^3.0.1",
    "eslint-plugin-vue": "^4.0.0-beta.4",
    "vue": "^2.5.13",
  }
}
```
**.eslintrc.js**

```
module.exports = {
  root: true,
  parserOptions: {
    parser: 'babel-eslint',
    ecmaVersion: 2017,
    sourceType: 'module'
  },
  env: {
    browser: true,
    node: true
  },
  extends: [
    'standard',
    'plugin:vue/recommended',
    './.eslint-plugin-jdi.js' // This file contains our own rules
  ]
}
```

Currently running the following versions:
```
Node: 8.5.0
ESlint: 4.14.0
```

I have no idea if this is the right place to start looking, but when I disable the plugin I get propper feedback, so I figured maybe you can help.

**Comment by feross** [comment]
This issue has been open for a while so it's probably stale. I'm going to close it for now.

If you're still experiencing this issue, please leave a comment or open a new issue.
